config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  namespace :certification do
    resources :tracks do
      resources :categories, only: [:new] do
        collection do
          put "batch_update"
          put "batch_destroy"
        end
      end
    end
  end

  resources :users, only: [:index, :edit, :update] do
    get 'results'
  end

  get "/available", to: "question_set/categories#exam_list"

  namespace :exam do
    resources :lists, only: [:show, :update] do

      collection do
        get 'find'
      end
    end

    resources :questions, only: [:update]
  end

  namespace :question_set do
    resources :categories, only: [:index, :new, :create, :edit, :update, :show] do
      resources :questions do

        collection do
          match 'search' => 'questions#search', via: [:get], as: :search
        end

        member do
          put "archive"
        end
      end

      get "results"

      member do
        put "archive"
      end
    end
  end

  root "question_set/categories#exam_list"
end

app/models/question_set.rb
module QuestionSet
  def self.table_name_prefix
    'question_set_'
  end
end

app/models/question_set/category.rb
class QuestionSet::Category < ActiveRecord::Base
  validates :name, :max_question, presence: true

  has_many :questions, class_name: "QuestionSet::Question", inverse_of: :category

  has_and_belongs_to_many :tracks, class_name: "Certification::Track", join_table: :certification_tracks_categories

  accepts_nested_attributes_for :questions, allow_destroy: true

  scope :active, -> { where(archived_at: nil) }
  scope :enabled, -> { where(enabled: true) }
  scope :where_name_like, -> (text) { where("name ilike ?", "%#{text}%") }
end

app/models/question_set/choice.rb
class QuestionSet::Choice < ActiveRecord::Base
  validates :text, :question, presence: true

  belongs_to :question, class_name: "QuestionSet::Question", inverse_of: :choices
end

app/models/question_set/question.rb
class QuestionSet::Question < ActiveRecord::Base
  before_save :atleast_two_choices

  belongs_to :category, class_name: "QuestionSet::Category", inverse_of: :questions
  has_many :choices, class_name: "QuestionSet::Choice", inverse_of: :question
  accepts_nested_attributes_for :choices, allow_destroy: true, reject_if: :reject_question

  validates :text, presence: true

  scope :active, -> { where(archived_at: nil) }
  scope :where_text_like, -> (text) { where("text ilike ?", "%#{text}%") }
  scope :by_category_id, -> (id) { where("category_id = ?", id) }

  def correct_answer
    self.choices.where(answer: true).first
  end

  private

  def reject_question(attrb)
    attrb['text'].blank? && self.persisted?
  end

  def atleast_two_choices
    if self.choices.size < 2
      self.errors.add(:base, "Should have at least 2 choices.")
      return false
    else
      return true
    end
  end
end

app/controllers/certification/categories_controller.rb
class Certification::CategoriesController < ApplicationController
  before_filter :authorized?

  def new
    @track = Certification::Track.find(params[:track_id])
    @categories = QuestionSet::Category.all
  end

  def batch_destroy
    @track = Certification::Track.find(params[:track_id])

    params["category"].each do |id|
      category = QuestionSet::Category.find(id)
      @track.categories.delete(category)
    end

    flash[:notice] = "#{params['category'].count} categories have been removed."
    redirect_to certification_track_path(@track)
  end

  def batch_update
    @track = Certification::Track.find(params[:track_id])
    @categories = []

    params["category"].each do |id|
      @categories << QuestionSet::Category.find(id)
    end

    if @track.categories << @categories
      flash[:notice] = "#{@categories.count} categories have been added."
      redirect_to certification_track_path(@track)
    else
      render "new"
    end
  end
end

app/controllers/question_set/categories_controller.rb
class QuestionSet::CategoriesController < ApplicationController
  before_filter :authorized?, except: [:exam_list, :results]

  def index
    @q = QuestionSet::Category.active.ransack(params[:q])
    @categories = @q.result.order("name").page(params[:page])
  end

  def show
    @category = QuestionSet::Category.find(params[:id])
    @questions = @category.questions.order("text").page(params[:page])
  end

  def new
    @category = QuestionSet::Category.new
  end

  def create
    @category = QuestionSet::Category.create(category_params)

    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to question_set_category_questions_path(@category)
    else
      render "new"
    end
  end

  def edit
    @category = QuestionSet::Category.find(params[:id])
  end

  def update
    @category = QuestionSet::Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = 'Category was successfully updated.'
      redirect_to question_set_category_questions_path(@category)
    else
      render "edit"
    end
  end

  # Archive a category
  def archive
    @category = QuestionSet::Category.find(params[:id])

    if @category.update_attributes(archived_at: DateTime.now)
      flash[:notice] = 'Category was successfully deleted.'
      redirect_to question_set_categories_path
    else
      render "index"
    end
  end

  def results
    @category = QuestionSet::Category.find(params[:category_id])
    @exams = Exam::List.where("category_id = ? AND user_id = ?", @category.id, current_user.id)

    respond_to do |format|
      format.html
      format.json { render json: @exams, root: false }
    end
  end

  def exam_list
    @track = current_user.track
    @active = @track.categories.active
    @enabled = @active.enabled.where_name_like(params[:keywords])
    @page = (params[:page] || 0).to_i
    # TODO change the page size or create pagination
    @page_size  = (params[:page_size] || 10000).to_i
    @categories = @enabled.offset(@page_size * @page).limit(@page_size).order("name")

    respond_to do |format|
      format.html
      format.json {
        render json: @categories,
               each_serializer: QuestionSet::CategoryAvailableSerializer,
               meta: { total_count: @enabled.count }
      }
    end
  end

  private

  def category_params
    params.require(:question_set_category).permit(:name, :max_question, :enabled)
  end
end

app/controllers/question_set/questions_controller.rb
class QuestionSet::QuestionsController < ApplicationController
  before_filter :authorized?

  def index
    @category = QuestionSet::Category.find(params[:category_id])
    @q = @category.questions.active.ransack(params[:q])
    @questions = @q.result.order("text").page(params[:page])
  end

  def search
    index
    render :index
  end

  def new
    @category = QuestionSet::Category.find(params[:category_id])
    @question = @category.questions.new
  end

  def edit
    @category = QuestionSet::Category.find(params[:category_id])
    @question = QuestionSet::Question.find(params[:id])
  end

  def show
    render json: QuestionSet::Question.find(params[:id])
  end

  def create
    @category = QuestionSet::Category.find(params[:category_id])

    if QuestionSet::Question.create(question_params)
      flash[:notice] = 'Question was successfully added.'
      render nothing: true, status: 204
    else
      render json: { errors: @question.errors.to_a }, status: :unprocessable_entity
    end
  end

  def update
    @question = QuestionSet::Question.find(params[:id])

    if @question.update(question_params)
      flash[:notice] = 'Question was successfully updated.'
      render nothing: true, status: 204
    else
      render json: { errors: @question.errors.to_a }, status: :unprocessable_entity
    end
  end

  # Archive a question
  def archive
    @category = QuestionSet::Category.find(params[:category_id])
    @question = QuestionSet::Question.find(params[:id])

    if @question.update_attributes(archived_at: DateTime.now)
      flash[:notice] = 'Question was successfully deleted.'
      redirect_to question_set_category_questions_path(@category)
    else
      render "index"
    end
  end

  private

  def question_params
    params.require(:question).permit(:text, :category_id, choices_attributes: [:id, :text, :answer, :_destroy])
  end
end

app/views/question_set/categories/_breadcrumbs.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><a href="/question_set/categories">Categories</a></li>
  <li class="active">
    <% if @category.new_record? %>
      New Category
    <% else %>
      Category #<%= @category.id %>
    <% end %>
  </li>
</ul>

app/views/question_set/categories/_form.html.erb
<%= form_for(@category, html: { name: "form", class: "form-horizontal" }) do |f| %>
  <div class="form-group" ng-class="{ 'has-error' : fieldIsValid(form['question_set_category[name]']) }">
    <label for="text" class="col-sm-2 control-label">Category Name
      <span style="color:red;">*</span>
    </label>
    <div class="col-sm-10">
      <input type="text" id="question_set_category_name" name="question_set_category[name]" class="form-control" placeholder="Name" autofocus="autofocus" ng-model="category.name" required>
      <p ng-show="fieldIsValid(form['question_set_category[name]'])" class="error">Category Name is required.</p>
    </div>
  </div>
  <div class="form-group" ng-class="{ 'has-error' : fieldIsValid(form['question_set_category[max_question]']) }">
    <label for="text" class="col-sm-2 control-label">Max Question
      <span style="color:red;">*</span>
    </label>
    <div class="col-sm-10">
      <input type="text" id="question_set_category_max_question" name="question_set_category[max_question]" class="form-control" placeholder="Max Question" ng-model="category.max_question" min=0 ng-pattern="onlyNumbers" required>
      </input>
      <p ng-show="fieldIsValid(form['question_set_category[max_question]'])" class="error">Max question is required and should be an integer.
      </p>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="togglebutton">
        <label>
          <%= f.check_box :enabled %> Enabled
        </label>
      </div>
    </div>
  </div>
  <button style="visibility: hidden"></button>
  <div class="text-right">
    <%= f.submit "OK", class: "btn btn-primary", ng_disabled: "form.$invalid" %>
    <%= link_to "Cancel", :back, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/question_set/categories/_question_form.html.erb
<form name="questionForm" ng-submit="ok(questionForm.$invalid)" class="form-horizontal" novalidate>
  <div class="modal-header">
    <h3 class="modal-title">{{title}}</h3>
    <hr />
  </div>
  <div class="modal-body">
    <div class="alert alert-danger alert-dismissible fade in" role="alert" ng-if="showError == true">
      <a class="close" data-dismiss="alert" aria-label="Close">x
      </a>
      <strong>An error occurred:</strong>
      <ul>
        <li ng-repeat="error in errors">
          {{error}}
        </li>
      </ul>
    </div>

    <div class="form-group" ng-class="{ 'has-error' : questionForm.text.$invalid && !questionForm.text.$pristine }">
      <label for="text" class="col-sm-2 control-label">Question Text
        <span style="color:red;">*</span>
      </label>
      <div class="col-sm-10">
        <input type="text" id="text" name="text" class="form-control" placeholder="Question Text" ng-model="text" autofocus="autofocus" required>

        <p ng-show="questionForm.text.$invalid && !questionForm.text.$pristine" class="error">Question text is required.</p>
      </div>
    </div>
    <div class="text-right">
      <a ng-click="addChoice($event)" class="btn btn-info btn-sm">
        <i class="glyphicon glyphicon-plus"></i>
        Add new choice
      </a>
    </div>
    <table class="table table-responsive table-borderless">
      <tr ng-repeat="choice in choices | filter: hideDeletedChoice">
        <td class="table-row-borderless text-center" style="width: 15px;">
          <div class="radio radio-primary">
            <label>
              <input type="radio" name="answer" ng-model="selectedChoice" ng-value="choice" ng-click="setAnswer(choice)">
            </label>
          </div>
        </td>
        <td class="table-row-borderless">
          <div ng-form="choiceForm">
            <div class="form-group" ng-class="{ 'has-error' : choiceForm.text.$invalid && !choiceForm.text.$pristine }">
              <label for="choiceText" class="col-sm-2 control-label">Choice #{{$index + 1}}</label>
              <div class="col-sm-10">
                <input type="text" id="text" name="text" class="form-control" placeholder="Choice Text #{{$index + 1}}" ng-model="choice.text" required>

                <p ng-show="choiceForm.text.$invalid && !choiceForm.text.$pristine" class="error">Choice text #{{$index + 1}} is required.
                </p>
              </div>
            </div>
          </div>
        </td>
        <td class="table-row-borderless" style="width: 15px;">
           <a class="btn pull-right" ng-click="removeChoice(choice, $event)">
            <i class="glyphicon glyphicon-trash text-primary"></i>
          </a>
        </td>
      </tr>
    </table>

    <!-- Hack to allow pressing an enter
      See: http://bit.ly/1PFVejf
    -->
    <button style="visibility: hidden"></button>
  </div>
  <div class="modal-footer">
    <hr />
    <button class="btn btn-primary" type="button" ng-click="ok(questionForm.$invalid)" ng-disabled="questionForm.$invalid">OK</button>
    <button class="btn btn-warning" type="button" ng-click="cancel()">Cancel</button>
  </div>
</form>

app/views/question_set/categories/edit.html.erb
<div ng-controller="CategoryController" ng-init="init('<%= @category.to_json %>')">
  <%= render partial: "breadcrumbs" %>
  <%= render "form" %>
</div>

app/views/question_set/categories/exam_list.html.erb
<div ng-controller="AvailableController">
  <ul class="breadcrumb">
    <li class="active">Home</li>
  </ul>

    <div class="table-responsive">
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th style="width: 100px;">Final Grade</th>
          <th style="width: 60px;">Attempts</th>
          <th style="width: 60px;">Actions</th>
        </tr>
      </thead>
      <tbody data-link="row" class="rowlink">
        <tr ng-repeat="category in categories">
          <td class="rowlink-skip">
            {{category.name}}
          </td>
          <td class="rowlink-skip text-center">
            <div ng-class="{'text-success': examPassed(category), 'text-warning': !examPassed(category)}">
              <b>{{showGrade(category)}} </b>
            </div>
          </td>
          <td class="rowlink-skip text-center">
            <u>
              <a ng-href="/question_set/categories/{{category.id}}/results">
                {{category.attempts}}
              </a>
            </u>
          </td>
          <td class="rowlink-skip text-center vert-middle">
            <button class="btn bootstrap" ng-click="start(category)" ng-disabled="examPassed(category)">
              <i class="glyphicon glyphicon-play" ng-class="{'text-primary': !examPassed(category)}"></i>
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/question_set/categories/index.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Categories</li>
</ul>

<div class="row vertical-align">
  <div class="col-sm-9 col-xs-6 col-md-9">
    <%= link_to "Add Category", new_question_set_category_path(), class: "btn btn-primary btn-sm" %>
  </div>

  <div class="col-sm-3 col-xs-6 col-md-3 vcenter">
    <%= search_form_for @q do |f| %>
      <%= f.search_field :name_cont, class: "form-control", placeholder: "Search" %>
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th style="width: 10px;">Max</th>
        <th style="width: 60px;">Enabled</th>
        <th style="width: 100px;">Actions</th>
      </tr>
    </thead>
    <tbody data-link="row" class="rowlink">
      <% @categories.each do |category| %>
        <tr>
          <td>
            <%= link_to category.name, question_set_category_questions_path(category) %>
          </td>
          <td>
            <a>
              <%= category.max_question %>
            </a>
          </td>
          <td class="text-center">
            <% if category.enabled %>
              <i class="glyphicon glyphicon-ok"></i>
            <% end %>
          </td>
          <td class="rowlink-skip text-center vert-middle">
            <%= link_to edit_question_set_category_path(category.id), class: "btn bootstrap" do %>
              <i class="glyphicon glyphicon-edit text-primary"></i>
            <% end %>
            <%= link_to archive_question_set_category_path(category), method: :put, data: {confirm: "Are you sure?" }, class: "btn bootstrap" do %>
              <i class="glyphicon glyphicon-trash text-primary"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <div class="text-center">
    <%= page_entries_info @categories %>
  </div>
  <div class="text-center">
    <%= paginate @categories %>
  </div>
</div>

app/views/question_set/categories/new.html.erb
<div ng-controller="CategoryController">
  <ul class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><a href="/question_set/categories">Categories</a></li>
    <li class="active">Category</li>
  </ul>
  <br />

  <%= render "form" %>
</div>

app/views/question_set/categories/results.html.erb
<div ng-controller="ExamResultController" ng-init="init('<%= @category.id %>')">
  <ul class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><%= link_to "Available Exams", available_path %></li>
    <li class="active">Results</li>
  </ul>

  <div class="text-center">
    <h3><%= @category.name %></h3>
  </div>

  <br />
  <div class="table-responsive">
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th>Score</th>
          <th>Completed At</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <tr ng-repeat="exam in exams">
          <td class="text-center">
            <div ng-class="{'text-success': examPassed(exam), 'text-warning': !examPassed(exam)}">
              <b>{{showGrade(exam)}} </b>
            </div>
          </td>
          <td class="text-center">
            {{exam.completed_at | date: 'medium'}}
          </td>
          <td class="text-center">
            <a ng-href="/exam/lists/{{exam.id}}">View</a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>