config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  namespace :certification do
    resources :tracks do
      resources :categories, only: [:new] do
        collection do
          put "batch_update"
          put "batch_destroy"
        end
      end
    end
  end

  resources :users, only: [:index, :edit, :update] do
    get 'results'
  end

  get "/available", to: "question_set/categories#exam_list"

  namespace :exam do
    resources :lists, only: [:show, :update] do

      collection do
        get 'find'
      end
    end

    resources :questions, only: [:update]
  end

  namespace :question_set do
    resources :categories, only: [:index, :new, :create, :edit, :update, :show] do
      resources :questions do

        collection do
          match 'search' => 'questions#search', via: [:get], as: :search
        end

        member do
          put "archive"
        end
      end

      get "results"

      member do
        put "archive"
      end
    end
  end

  root "question_set/categories#exam_list"
end

app/models/exam/question.rb
class Exam::Question < ActiveRecord::Base
  belongs_to :question_set_question, class_name: "QuestionSet::Question"
  belongs_to :list, class_name: "Exam::List", inverse_of: :questions

  has_many :choices, class_name: "Exam::Choice", inverse_of: :question
end

app/models/question_set.rb
module QuestionSet
  def self.table_name_prefix
    'question_set_'
  end
end

app/models/question_set/category.rb
class QuestionSet::Category < ActiveRecord::Base
  validates :name, :max_question, presence: true

  has_many :questions, class_name: "QuestionSet::Question", inverse_of: :category

  has_and_belongs_to_many :tracks, class_name: "Certification::Track", join_table: :certification_tracks_categories

  accepts_nested_attributes_for :questions, allow_destroy: true

  scope :active, -> { where(archived_at: nil) }
  scope :enabled, -> { where(enabled: true) }
  scope :where_name_like, -> (text) { where("name ilike ?", "%#{text}%") }
end

app/models/question_set/choice.rb
class QuestionSet::Choice < ActiveRecord::Base
  validates :text, :question, presence: true

  belongs_to :question, class_name: "QuestionSet::Question", inverse_of: :choices
end

app/models/question_set/question.rb
class QuestionSet::Question < ActiveRecord::Base
  before_save :atleast_two_choices

  belongs_to :category, class_name: "QuestionSet::Category", inverse_of: :questions
  has_many :choices, class_name: "QuestionSet::Choice", inverse_of: :question
  accepts_nested_attributes_for :choices, allow_destroy: true, reject_if: :reject_question

  validates :text, presence: true

  scope :active, -> { where(archived_at: nil) }
  scope :where_text_like, -> (text) { where("text ilike ?", "%#{text}%") }
  scope :by_category_id, -> (id) { where("category_id = ?", id) }

  def correct_answer
    self.choices.where(answer: true).first
  end

  private

  def reject_question(attrb)
    attrb['text'].blank? && self.persisted?
  end

  def atleast_two_choices
    if self.choices.size < 2
      self.errors.add(:base, "Should have at least 2 choices.")
      return false
    else
      return true
    end
  end
end

app/controllers/exam/questions_controller.rb
class Exam::QuestionsController < ApplicationController
  before_filter :check_privileges, only: [:update]

  def update
    @question = Exam::Question.find(params[:id])
    @list = @question.list

    @list.start! if @list.created?

    if @list.completed? || @question.update_attributes(question_params)
      render nothing: true, status: 204
    end
  end

  private

  def question_params
    params.require(:question).permit(:value)
  end

  def check_privileges
    exam = Exam::Question.find(params[:id]).list

    if exam.user != current_user
      flash[:alert] = "You are not authorized to view that page."
      redirect_to available_path
    end
  end
end

app/controllers/question_set/categories_controller.rb
class QuestionSet::CategoriesController < ApplicationController
  before_filter :authorized?, except: [:exam_list, :results]

  def index
    @q = QuestionSet::Category.active.ransack(params[:q])
    @categories = @q.result.order("name").page(params[:page])
  end

  def show
    @category = QuestionSet::Category.find(params[:id])
    @questions = @category.questions.order("text").page(params[:page])
  end

  def new
    @category = QuestionSet::Category.new
  end

  def create
    @category = QuestionSet::Category.create(category_params)

    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to question_set_category_questions_path(@category)
    else
      render "new"
    end
  end

  def edit
    @category = QuestionSet::Category.find(params[:id])
  end

  def update
    @category = QuestionSet::Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = 'Category was successfully updated.'
      redirect_to question_set_category_questions_path(@category)
    else
      render "edit"
    end
  end

  # Archive a category
  def archive
    @category = QuestionSet::Category.find(params[:id])

    if @category.update_attributes(archived_at: DateTime.now)
      flash[:notice] = 'Category was successfully deleted.'
      redirect_to question_set_categories_path
    else
      render "index"
    end
  end

  def results
    @category = QuestionSet::Category.find(params[:category_id])
    @exams = Exam::List.where("category_id = ? AND user_id = ?", @category.id, current_user.id)

    respond_to do |format|
      format.html
      format.json { render json: @exams, root: false }
    end
  end

  def exam_list
    @track = current_user.track
    @active = @track.categories.active
    @enabled = @active.enabled.where_name_like(params[:keywords])
    @page = (params[:page] || 0).to_i
    # TODO change the page size or create pagination
    @page_size  = (params[:page_size] || 10000).to_i
    @categories = @enabled.offset(@page_size * @page).limit(@page_size).order("name")

    respond_to do |format|
      format.html
      format.json {
        render json: @categories,
               each_serializer: QuestionSet::CategoryAvailableSerializer,
               meta: { total_count: @enabled.count }
      }
    end
  end

  private

  def category_params
    params.require(:question_set_category).permit(:name, :max_question, :enabled)
  end
end

app/controllers/question_set/questions_controller.rb
class QuestionSet::QuestionsController < ApplicationController
  before_filter :authorized?

  def index
    @category = QuestionSet::Category.find(params[:category_id])
    @q = @category.questions.active.ransack(params[:q])
    @questions = @q.result.order("text").page(params[:page])
  end

  def search
    index
    render :index
  end

  def new
    @category = QuestionSet::Category.find(params[:category_id])
    @question = @category.questions.new
  end

  def edit
    @category = QuestionSet::Category.find(params[:category_id])
    @question = QuestionSet::Question.find(params[:id])
  end

  def show
    render json: QuestionSet::Question.find(params[:id])
  end

  def create
    @category = QuestionSet::Category.find(params[:category_id])

    if QuestionSet::Question.create(question_params)
      flash[:notice] = 'Question was successfully added.'
      render nothing: true, status: 204
    else
      render json: { errors: @question.errors.to_a }, status: :unprocessable_entity
    end
  end

  def update
    @question = QuestionSet::Question.find(params[:id])

    if @question.update(question_params)
      flash[:notice] = 'Question was successfully updated.'
      render nothing: true, status: 204
    else
      render json: { errors: @question.errors.to_a }, status: :unprocessable_entity
    end
  end

  # Archive a question
  def archive
    @category = QuestionSet::Category.find(params[:category_id])
    @question = QuestionSet::Question.find(params[:id])

    if @question.update_attributes(archived_at: DateTime.now)
      flash[:notice] = 'Question was successfully deleted.'
      redirect_to question_set_category_questions_path(@category)
    else
      render "index"
    end
  end

  private

  def question_params
    params.require(:question).permit(:text, :category_id, choices_attributes: [:id, :text, :answer, :_destroy])
  end
end

app/views/question_set/questions/_breadcrumbs.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to "Categories", question_set_categories_path %></li>
  <li><%= link_to "Category ##{@category.id}", question_set_category_questions_path(@category) %></li>
  <li class="active">
    <% if @question.new_record? %>
      New Question
    <% else %>
      Question #<%= @question.id %>
    <% end %>
  </li>
</ul>

app/views/question_set/questions/_form.html.erb
<div ng-controller="QuestionController" ng-init="init('<%= @category.id%>', '<%= @question.id %>')">
  <br /><br />
  <form name="form" ng-submit="ok(form.$invalid)" class="form-horizontal" novalidate>
    <div class="form-group" ng-class="{ 'has-error' : fieldIsValid(form.text) }">
      <label for="text" class="col-sm-2 control-label">Question Text
        <span style="color:red;">*</span>
      </label>
      <div class="col-sm-10">
        <input type="text" id="text" name="text" class="form-control" placeholder="Question Text" ng-model="text" autofocus="autofocus" required>

        <p ng-show="fieldIsValid(form.text)" class="error">Question text is required.</p>
      </div>
    </div>

    <div class="text-right">
      <a ng-click="addChoice($event)" class="btn btn-info btn-sm">
        <i class="glyphicon glyphicon-plus"></i>
        Add new choice
      </a>
    </div>

    <table class="table table-responsive table-borderless">
      <tr ng-repeat="choice in choices | filter: hideDeletedChoice">
        <td class="table-row-borderless text-center" style="width: 15px;">
          <div class="radio radio-primary">
            <label>
              <input type="radio" name="answer" ng-model="selectedChoice" ng-value="choice" ng-click="setAnswer(choice)">
            </label>
          </div>
        </td>
        <td class="table-row-borderless">
          <div ng-form="choiceForm">
            <div class="form-group" ng-class="{ 'has-error' : fieldIsValid(choiceForm.text) }">
              <label for="choiceText" class="col-sm-2 control-label">Choice #{{$index + 1}}</label>
              <div class="col-sm-10">
                <input type="text" id="text" name="text" class="form-control" placeholder="Choice Text #{{$index + 1}}" ng-model="choice.text" required>

                <p ng-show="fieldIsValid(choiceForm.text)" class="error">Choice text #{{$index + 1}} is required.
                </p>
              </div>
            </div>
          </div>
        </td>
        <td class="table-row-borderless" style="width: 15px;">
           <a class="btn pull-right" ng-click="removeChoice(choice, $event)">
            <i class="glyphicon glyphicon-trash text-primary"></i>
          </a>
        </td>
      </tr>
    </table>

    <!-- Hack to allow pressing an enter
      See: http://bit.ly/1PFVejf
    -->
    <button style="visibility: hidden"></button>
    <div class="text-right">
      <button class="btn btn-primary" type="button" ng-click="ok(form.$invalid)" ng-disabled="form.$invalid">OK</button>
      <%= link_to 'Cancel', url_for(:back), class: "btn btn-warning" %>
    </div>
  </form>
</div>

app/views/question_set/questions/_header.html.erb
<div class="table-responsive">
  <table class="table table-bordered">
    <tr>
      <td style="width: 200px;"><b>Category</b></td>
      <td><%= @category.name %> <sup><%= link_to "(Edit)", edit_question_set_category_path(@category) %></sup>
      </td>
    </tr>
    <tr>
      <td><b>Max Questions</b></td>
      <td><%= @category.max_question %></td>
    </tr>
    <tr>
      <td><b>Enabled</b></td>
      <td><%= @category.enabled.to_s.capitalize %></td>
    </tr>
  </table>
</div>

app/views/question_set/questions/edit.html.erb
<%= render partial: "breadcrumbs" %>
<%= render partial: "header" %>
<%= render "form" %>

app/views/question_set/questions/index.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to "Categories", question_set_categories_path %></li>
  <li class="active">Category #<%= @category.id %></li>
</ul>

<%= render partial: "header" %>

<h2>Questions</h2>
<div class="row">
  <div class="col-sm-9 col-xs-6 col-md-9">
    <%= link_to "Add Question", new_question_set_category_question_path(@category), class: "btn btn-primary btn-sm" %>
  </div>
  <div class="col-sm-3 col-xs-6 col-md-3 ">
    <%= search_form_for @q, url: search_question_set_category_questions_path do |f| %>
      <%= f.search_field :text_cont, class: "form-control", placeholder: "Search" %>
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Text</th>
        <th style="width: 50px;"></th>
      </tr>
    </thead>
    <tbody data-link="row" class="rowlink">
      <% @questions.each do |question| %>
        <tr>
          <td class="vert-align">
            <%= link_to question.text, edit_question_set_category_question_path(@category, question), class: "btn bootstrap" %>
          </td>
          <td class="rowlink-skip text-center">
            <%= link_to archive_question_set_category_question_path(@category, question), data: { confirm: "Are you sure?" }, class:"btn bootstrap", method: :put do %>
              <i class="glyphicon glyphicon-trash text-primary"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <div class="text-center">
    <%= page_entries_info @questions %>
  </div>
  <div class="text-center">
    <%= paginate @questions %>
  </div>
</div>

app/views/question_set/questions/new.html.erb
<%= render partial: "breadcrumbs" %>
<%= render partial: "header" %>
<%= render "form" %>