config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  namespace :certification do
    resources :tracks do
      resources :categories, only: [:new] do
        collection do
          put "batch_update"
          put "batch_destroy"
        end
      end
    end
  end

  resources :users, only: [:index, :edit, :update] do
    get 'results'
  end

  get "/available", to: "question_set/categories#exam_list"

  namespace :exam do
    resources :lists, only: [:show, :update] do

      collection do
        get 'find'
      end
    end

    resources :questions, only: [:update]
  end

  namespace :question_set do
    resources :categories, only: [:index, :new, :create, :edit, :update, :show] do
      resources :questions do

        collection do
          match 'search' => 'questions#search', via: [:get], as: :search
        end

        member do
          put "archive"
        end
      end

      get "results"

      member do
        put "archive"
      end
    end
  end

  root "question_set/categories#exam_list"
end

app/models/certification.rb
module Certification
  def self.table_name_prefix
    'certification_'
  end
end

app/models/certification/track.rb
class Certification::Track < ActiveRecord::Base
  validates :name, presence: true

  has_many :users
  has_and_belongs_to_many :categories, class_name: "QuestionSet::Category", join_table: :certification_tracks_categories

  scope :enabled, -> { where(enabled: true) }
end

app/models/question_set/category.rb
class QuestionSet::Category < ActiveRecord::Base
  validates :name, :max_question, presence: true

  has_many :questions, class_name: "QuestionSet::Question", inverse_of: :category

  has_and_belongs_to_many :tracks, class_name: "Certification::Track", join_table: :certification_tracks_categories

  accepts_nested_attributes_for :questions, allow_destroy: true

  scope :active, -> { where(archived_at: nil) }
  scope :enabled, -> { where(enabled: true) }
  scope :where_name_like, -> (text) { where("name ilike ?", "%#{text}%") }
end

app/controllers/certification/categories_controller.rb
class Certification::CategoriesController < ApplicationController
  before_filter :authorized?

  def new
    @track = Certification::Track.find(params[:track_id])
    @categories = QuestionSet::Category.all
  end

  def batch_destroy
    @track = Certification::Track.find(params[:track_id])

    params["category"].each do |id|
      category = QuestionSet::Category.find(id)
      @track.categories.delete(category)
    end

    flash[:notice] = "#{params['category'].count} categories have been removed."
    redirect_to certification_track_path(@track)
  end

  def batch_update
    @track = Certification::Track.find(params[:track_id])
    @categories = []

    params["category"].each do |id|
      @categories << QuestionSet::Category.find(id)
    end

    if @track.categories << @categories
      flash[:notice] = "#{@categories.count} categories have been added."
      redirect_to certification_track_path(@track)
    else
      render "new"
    end
  end
end

app/controllers/certification/tracks_controller.rb
class Certification::TracksController < ApplicationController
  before_filter :authorized?

  def index
    @tracks = Certification::Track.all
  end

  def new
    @track = Certification::Track.new
  end

  def show
    @track = Certification::Track.find(params[:id])
    @categories = @track.categories
  end

  def edit
    @track = Certification::Track.find(params[:id])
  end

  def update
    @track = Certification::Track.find(params[:id])

    if @track.update_attributes(track_params)
      flash[:notice] = 'Certification Track was successfully updated.'
      redirect_to certification_track_path(@track)
    else
      render "edit"
    end
  end

  def create
    @track = Certification::Track.new(track_params)

    if @track.save
      flash[:notice] = 'Certification Track was successfully created.'
      redirect_to certification_track_path(@track)
    else
      render "new"
    end
  end

  private

  def track_params
    params.require(:certification_track).permit(:enabled, :name)
  end
end

app/controllers/question_set/categories_controller.rb
class QuestionSet::CategoriesController < ApplicationController
  before_filter :authorized?, except: [:exam_list, :results]

  def index
    @q = QuestionSet::Category.active.ransack(params[:q])
    @categories = @q.result.order("name").page(params[:page])
  end

  def show
    @category = QuestionSet::Category.find(params[:id])
    @questions = @category.questions.order("text").page(params[:page])
  end

  def new
    @category = QuestionSet::Category.new
  end

  def create
    @category = QuestionSet::Category.create(category_params)

    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to question_set_category_questions_path(@category)
    else
      render "new"
    end
  end

  def edit
    @category = QuestionSet::Category.find(params[:id])
  end

  def update
    @category = QuestionSet::Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = 'Category was successfully updated.'
      redirect_to question_set_category_questions_path(@category)
    else
      render "edit"
    end
  end

  # Archive a category
  def archive
    @category = QuestionSet::Category.find(params[:id])

    if @category.update_attributes(archived_at: DateTime.now)
      flash[:notice] = 'Category was successfully deleted.'
      redirect_to question_set_categories_path
    else
      render "index"
    end
  end

  def results
    @category = QuestionSet::Category.find(params[:category_id])
    @exams = Exam::List.where("category_id = ? AND user_id = ?", @category.id, current_user.id)

    respond_to do |format|
      format.html
      format.json { render json: @exams, root: false }
    end
  end

  def exam_list
    @track = current_user.track
    @active = @track.categories.active
    @enabled = @active.enabled.where_name_like(params[:keywords])
    @page = (params[:page] || 0).to_i
    # TODO change the page size or create pagination
    @page_size  = (params[:page_size] || 10000).to_i
    @categories = @enabled.offset(@page_size * @page).limit(@page_size).order("name")

    respond_to do |format|
      format.html
      format.json {
        render json: @categories,
               each_serializer: QuestionSet::CategoryAvailableSerializer,
               meta: { total_count: @enabled.count }
      }
    end
  end

  private

  def category_params
    params.require(:question_set_category).permit(:name, :max_question, :enabled)
  end
end

app/views/certification/categories/_index.html.erb
<%= form_for(@track, url: batch_destroy_certification_track_categories_path(@track), method: :put) do |f|%>
  <%= link_to "Add Categories", new_certification_track_category_path(@track), class: "btn btn-primary btn-sm" %>
  <%= f.submit "Delete Categories", class: "btn btn-danger btn-sm" %>

  <div class="table-responsive">
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th colspan="3" class="text-center">Categories</th>
        </tr>
        <tr>
          <th style="width: 60px;"></th>
          <th>Name</th>
          <th style="width: 60px;">Enabled</th>
        </tr>
      </thead>
      <tbody data-link="row" class="rowlink">
        <% @categories.each do |category| %>
          <tr>
            <td class="rowlink-skip text-center">
              <div class="checkbox">
                <label>
                  <%= check_box_tag "category[]", category.id %>
                </label>
              </div>
            </td>
            <td>
              <%= link_to category.name, edit_question_set_category_path(category.id) %>
            </td>
            <td class="rowlink-skip text-center">
              <% if category.enabled %>
                <div>
                  <i class="glyphicon glyphicon-ok"></i>
                </div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/certification/categories/new.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to "Certification Track", certification_tracks_path %></li>
  <li class="active"><%= link_to "Track #" %></li>
  <li class="active">Adding Categories</li>
</ul>

<%= render partial: "certification/tracks/track_header" %>

<%= form_for(@track, url: batch_update_certification_track_categories_path(@track), method: :put) do |f|%>

  <%= f.submit "Add to my category", class: "btn btn-primary btn-sm" %>
  <%= link_to "Cancel", :back, class: "btn btn-warning btn-sm" %>

  <div class="table-responsive">
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th colspan="3" class="text-center">Categories</th>
        </tr>
        <tr>
          <th style="width: 60px;"></th>
          <th>Name</th>
          <th style="width: 60px;">Enabled</th>
        </tr>
      </thead>
      <tbody data-link="row" class="rowlink">
        <% @categories.each do |category| %>
          <tr>
            <td class="rowlink-skip text-center">
              <% if @track.categories.include?(category) %>
                <i class="mdi-toggle-check-box"></i>
              <% else %>
                <div class="checkbox">
                  <label>
                    <%= check_box_tag "category[]", category.id %>
                  </label>
                </div>
              <% end %>
            </td>
            <td>
              <%= link_to category.name, edit_question_set_category_path(category.id) %>
            </td>
            <td class="rowlink-skip text-center">
              <% if category.enabled %>
                <div>
                  <i class="glyphicon glyphicon-ok"></i>
                </div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>