config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  namespace :certification do
    resources :tracks do
      resources :categories, only: [:new] do
        collection do
          put "batch_update"
          put "batch_destroy"
        end
      end
    end
  end

  resources :users, only: [:index, :edit, :update] do
    get 'results'
  end

  get "/available", to: "question_set/categories#exam_list"

  namespace :exam do
    resources :lists, only: [:show, :update] do

      collection do
        get 'find'
      end
    end

    resources :questions, only: [:update]
  end

  namespace :question_set do
    resources :categories, only: [:index, :new, :create, :edit, :update, :show] do
      resources :questions do

        collection do
          match 'search' => 'questions#search', via: [:get], as: :search
        end

        member do
          put "archive"
        end
      end

      get "results"

      member do
        put "archive"
      end
    end
  end

  root "question_set/categories#exam_list"
end

app/models/certification.rb
module Certification
  def self.table_name_prefix
    'certification_'
  end
end

app/models/certification/track.rb
class Certification::Track < ActiveRecord::Base
  validates :name, presence: true

  has_many :users
  has_and_belongs_to_many :categories, class_name: "QuestionSet::Category", join_table: :certification_tracks_categories

  scope :enabled, -> { where(enabled: true) }
end

app/controllers/certification/categories_controller.rb
class Certification::CategoriesController < ApplicationController
  before_filter :authorized?

  def new
    @track = Certification::Track.find(params[:track_id])
    @categories = QuestionSet::Category.all
  end

  def batch_destroy
    @track = Certification::Track.find(params[:track_id])

    params["category"].each do |id|
      category = QuestionSet::Category.find(id)
      @track.categories.delete(category)
    end

    flash[:notice] = "#{params['category'].count} categories have been removed."
    redirect_to certification_track_path(@track)
  end

  def batch_update
    @track = Certification::Track.find(params[:track_id])
    @categories = []

    params["category"].each do |id|
      @categories << QuestionSet::Category.find(id)
    end

    if @track.categories << @categories
      flash[:notice] = "#{@categories.count} categories have been added."
      redirect_to certification_track_path(@track)
    else
      render "new"
    end
  end
end

app/controllers/certification/tracks_controller.rb
class Certification::TracksController < ApplicationController
  before_filter :authorized?

  def index
    @tracks = Certification::Track.all
  end

  def new
    @track = Certification::Track.new
  end

  def show
    @track = Certification::Track.find(params[:id])
    @categories = @track.categories
  end

  def edit
    @track = Certification::Track.find(params[:id])
  end

  def update
    @track = Certification::Track.find(params[:id])

    if @track.update_attributes(track_params)
      flash[:notice] = 'Certification Track was successfully updated.'
      redirect_to certification_track_path(@track)
    else
      render "edit"
    end
  end

  def create
    @track = Certification::Track.new(track_params)

    if @track.save
      flash[:notice] = 'Certification Track was successfully created.'
      redirect_to certification_track_path(@track)
    else
      render "new"
    end
  end

  private

  def track_params
    params.require(:certification_track).permit(:enabled, :name)
  end
end

app/views/certification/tracks/_breadcrumbs.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to "Certification Track", certification_tracks_path %></li>
  <li class="active">
    <% if @track.new_record? %>
      New Track
    <% else %>
      Track #<%= @track.id %>
    <% end %>
  </li>
</ul>

app/views/certification/tracks/_form.html.erb
<%= form_for(@track, html: { name: "form", class: "form-horizontal" }) do |f| %>
  <div ng-controller="CertificationTrackController" ng-init="init('<%= @track.name %>', <%= @track.enabled %>)">

    <div class="form-group" ng-class="{ 'has-error' : fieldIsValid(form['certification_track[name]']) }">
      <label for="text" class="col-sm-2 control-label">Track Name
        <span style="color:red;">*</span>
      </label>
      <div class="col-sm-10">
        <input id="certification_track_name" name="certification_track[name]" class="form-control" placeholder="Track Name" autofocus="autofocus" type="text" ng-model="track.name" required>
        <p class="error" ng-show="fieldIsValid(form['certification_track[name]'])">Track Name is required.
        </p>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="togglebutton">
          <label>
            <%= f.check_box :enabled %> Enabled
          </label>
        </div>
      </div>
    </div>

    <div class="text-right">
      <%= f.submit "Submit", class: "btn btn-primary", ng_disabled: "form.$invalid" %>
      <%= link_to "Cancel", certification_tracks_path, class: "btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/certification/tracks/_track_header.html.erb
<div class="table-responsive">
  <table class="table table-bordered">
    <tr>
      <td style="width: 200px;"><b>Certification Track</b></td>
      <td><%= @track.name %> <sup><%= link_to "(Edit)", edit_certification_track_path(@track) %></sup>
      </td>
    </tr>
    <tr>
      <td><b>Enabled</b></td>
      <td><%= @track.enabled.to_s.capitalize %></td>
    </tr>
  </table>
</div>

app/views/certification/tracks/edit.html.erb
<%= render partial: "breadcrumbs" %>
<%= render partial: "form" %>

app/views/certification/tracks/index.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Certification Track</li>
</ul>

<br/>

<%= button_to "Add Track", new_certification_track_path, class: "btn btn-primary btn-sm", :method => :get %>

<div class="table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th style="width: 60px;">Enabled</th>
        <th style="width: 80px;">Actions</th>
      </tr>
    </thead>
    <tbody data-link="row" class="rowlink">
      <% @tracks.each do |track| %>
        <tr>
          <td>
            <%= link_to track.name, certification_track_path(track.id) %>
          </td>
          <td class="rowlink-skip text-center">
            <% if track.enabled %>
              <div>
                <i class="glyphicon glyphicon-ok"></i>
              </div>
            <% end %>
          </td>
          <td class="rowlink-skip text-center">
            <%= link_to edit_certification_track_path(track), class: "btn bootstrap" do %>
              <i class="glyphicon glyphicon-edit text-primary"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/certification/tracks/new.html.erb
<%= render partial: "breadcrumbs" %>
<%= render partial: "form" %>

app/views/certification/tracks/show.html.erb
<%= render partial: "breadcrumbs" %>
<%= render partial: "track_header" %>
<%= render :partial => "certification/categories/index"%>